#Discord Bot
discord.token=
#Canal do chat discord
discord.channelId = 
#HTTPS PORT
quarkus.http.ssl-port=8444
#Certificados de JWT
quarkus.http.ssl.certificate.key-store-file=keystore.jks
quarkus.http.ssl.certificate.key-store-password=password
smallrye.jwt.sign.key.location=privateKey.pem
quarkus.tls.trust-all=true
mp.jwt.verify.issuer=https://localhost:8444
mp.jwt.verify.publickey.location=publicKey.pem
# Configurações do cliente REST
quarkus.rest-client."org.acme.weatherapi.OpenWeatherClient".url=http://api.openweathermap.org
quarkus.rest-client."org.acme.weatherapi.OpenWeatherClient".scope=javax.inject.Singleton


