# Openweather API
quarkus.rest-client."org.acme.weatherapi.OpenWeatherClient".url=http://api.openweathermap.org
quarkus.rest-client."org.acme.weatherapi.OpenWeatherClient".scope=javax.inject.Singleton
openweather.api.key=aae9850a4549a27a854a33d4b60c5629
#HTTP/HTTPS configuração
quarkus.http.ssl-port=8443
quarkus.http.port=8081
#Certificados
quarkus.http.ssl.certificate.key-store-file=keystore.jks
quarkus.http.ssl.certificate.key-store-password=password
quarkus.tls.trust-all=true
